# Copyright (C) 2020 SiFive Inc
# SPDX-License-Identifier: Apache-2.0

RISCV_ARCH = rv64imafdc
RISCV_ABI = lp64d
RISCV_CMODEL = medany
RISCV_SERIES = sifive-7-series

TARGET_TAGS = rtl
TARGET_DHRY_ITERS = 2000
TARGET_CORE_ITERS = 5
TARGET_FREERTOS_WAIT_MS = 10

COREIP_MEM_WIDTH = 64