#!/bin/bash

set -e
set -o pipefail
set -x

targets=($(find bsp -name settings.mk | cut -d '/' -f 2)) 

programs=(hello return-pass minimal-boot example-freertos-minimal empty sifive-welcome timer-interrupt csr )

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

CONFIGURATION=debug

# Run regression tests
for target in ${targets[@]}
do
    for program in "${programs[@]}"
    do
        make TARGET="${target}" PROGRAM="${program}" CONFIGURATION="${CONFIGURATION}" -j${nproc} software
        make TARGET="${target}" PROGRAM="${program}" CONFIGURATION="${CONFIGURATION}" clean-software
    done
    make TARGET="${target}" clean
done

echo "PASSED"

