#!/bin/bash

set -euxo pipefail

targets=($(find bsp -name settings.mk | cut -d '/' -f 2)) 

programs=($(find software -name Makefile | cut -d '/' -f 2))

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

CONFIGURATION=debug

# Run regression tests
for target in ${targets[@]}
do
    for program in "${programs[@]}"
    do
        # Coremark and Dhrystone don't fit on all targets
        if [[ "${program}" == "dhrystone" ]] ; then continue; fi
        if [[ "${program}" == "coremark" ]] ; then continue; fi

        # Exclude CLIC, buserror, spi, HCA, and SystemView examples
        if [[ "${program}" == *"clic"* ]] ; then continue; fi
        if [[ "${program}" == *"buserror"* ]] ; then continue; fi

	# mc examples are broken
	if [[ "${program}" == "example-freertos-mc" ]]; then continue; fi
	if [[ "${program}" == "example-freertos-blinky-mc" ]]; then continue; fi

        make TARGET="${target}" PROGRAM="${program}" CONFIGURATION="${CONFIGURATION}" software
        make TARGET="${target}" PROGRAM="${program}" CONFIGURATION="${CONFIGURATION}" clean
    done
done

echo "PASSED"

