#!/bin/bash

DOCS_PATH="https://sifive.github.io/freedom-e-sdk-docs/index.html"

SDK_PATH="$1"

if [ "$SDK_PATH" != "" ]; then
    DOCS_PATH=$SDK_PATH/doc/html/index.html
fi

XDG_OPEN=`which xdg-open`
OPEN=`which open`

if [ "$XDG_OPEN" != "" ]; then
        echo "Opening $DOCS_PATH"
        $XDG_OPEN $DOCS_PATH

elif [ "$OPEN" != "" ]; then
        echo "Opening $DOCS_PATH"
        $OPEN $DOCS_PATH

else
        echo "Please open $DOCS_PATH in your preferred HTML viewer"
fi

