#!/bin/bash

set -e
set -o pipefail

unset elf
unset qemu
unset qemu_config
unset qemu_options
while [[ "$1" != "" ]]
do
    case "$1"
    in
    --elf)                   elf="$2";   shift 2;;
    --qemu)                 qemu="$2";   shift 2;;
    --qemu-config)   qemu_config="$2";   shift 2;;
    --qemu-options) qemu_options="$2";   shift 2;;
    *) echo "$0: Unknown argument $1";   exit 1;;
    esac
done

if [ "$elf" == "" ]
then
    echo "$0: --elf is required" >&2
    exit 1
fi
if [ "$qemu" == "" ]
then
    echo "$0: --qemu is required" >&2
    exit 1
else
    if [ "$qemu_config" == "" ]
    then
        echo "$0: --qemu_config is required" >&2
        exit 1
    fi
fi

if [ ! -f $qemu_config ] ; then
    echo "$0: Unable to find QEMU config file ${qemu_config}" >&2
    exit 1
fi

echo "Launching QEMU! Press Ctrl-A, X to exit"

$qemu -readconfig $qemu_config -kernel $elf -nographic $qemu_options

