name: tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        riscv_cflags: [
          "",
          "-std=c99 -Wall -Wextra -Wpedantic -Werror -Wno-unused-parameter",
        ]
        riscv_libc: [
          "",
        ]

    steps:
      - name: 'Clone freedom-e-sdk'
        uses: actions/checkout@v2
        with:
          path: freedom-e-sdk
          fetch-depth: 1
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build freedom-e-sdk container'
        run: |
          docker build -t freedom-e-sdk \
            -f freedom-e-sdk/docker/Dockerfile \
            freedom-e-sdk

      - name: 'Check BSP files are up-to-date'
        run: |
          docker run --rm freedom-e-sdk ./scripts/check-bsps-updated

      - name: 'Build all examples on all targets'
        run: |
          docker run --rm -e RISCV_CFLAGS="${{ matrix.riscv_cflags }}" -e RISCV_LIBC="${{ matrix.riscv_libc }}" freedom-e-sdk ./scripts/all-targets-build

      - name: 'Run examples on QEMU'
        run: |
          docker run --rm -e RISCV_CFLAGS="${{ matrix.riscv_cflags }}" -e RISCV_LIBC="${{ matrix.riscv_libc }}" freedom-e-sdk ./scripts/test-qemu-targets

      - name: 'Build examples as standalone projects'
        run: |
          docker run --rm -e RISCV_CFLAGS="${{ matrix.riscv_cflags }}" -e RISCV_LIBC="${{ matrix.riscv_libc }}" freedom-e-sdk ./scripts/test-standalone
